# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Accounts
Account.create!([
  {name: "First Account", balance: "147.7"},
  {name: "Second account", balance: "266.0"},
  {name: "Third account", balance: "841.3"},
  {name: "Forth account", balance: "1395.0"}
])

# Bank transactions
BankTransaction.create!([
  {debit_account_id: 1, credit_account_id: 2, amount: "30.0"},
  {debit_account_id: 1, credit_account_id: 2, amount: "30.0"},
  {debit_account_id: 1, credit_account_id: 2, amount: "30.0"},
  {debit_account_id: 1, credit_account_id: 2, amount: "30.0"},
  {debit_account_id: 2, credit_account_id: 1, amount: "30.0"},
  {debit_account_id: 2, credit_account_id: 1, amount: "5.0"},
  {debit_account_id: 2, credit_account_id: 1, amount: "5.5"},
  {debit_account_id: 2, credit_account_id: 1, amount: "5.5"},
  {debit_account_id: 2, credit_account_id: 1, amount: "34.7"},
  {debit_account_id: 4, credit_account_id: 1, amount: "10.0"},
  {debit_account_id: 4, credit_account_id: 1, amount: "10.0"},
  {debit_account_id: 4, credit_account_id: 1, amount: "10.0"},
  {debit_account_id: 4, credit_account_id: 3, amount: "10.0"},
  {debit_account_id: 4, credit_account_id: 3, amount: "10.0"},
  {debit_account_id: 4, credit_account_id: 3, amount: "10.0"},
  {debit_account_id: 4, credit_account_id: 3, amount: "10.0"},
  {debit_account_id: 2, credit_account_id: 3, amount: "10.0"},
  {debit_account_id: 2, credit_account_id: 3, amount: "10.0"},
  {debit_account_id: 2, credit_account_id: 3, amount: "15.0"},
  {debit_account_id: 2, credit_account_id: 1, amount: "15.0"},
  {debit_account_id: 2, credit_account_id: 1, amount: "15.0"},
  {debit_account_id: 4, credit_account_id: 3, amount: "155.0"},
  {debit_account_id: 4, credit_account_id: 3, amount: "155.0"},
  {debit_account_id: 2, credit_account_id: 4, amount: "35.0"},
  {debit_account_id: 2, credit_account_id: 4, amount: "35.0"},
  {debit_account_id: 2, credit_account_id: 4, amount: "35.0"},
  {debit_account_id: 4, credit_account_id: 2, amount: "35.0"},
  {debit_account_id: 4, credit_account_id: 2, amount: "35.0"},
  {debit_account_id: 4, credit_account_id: 2, amount: "23.7"},
  {debit_account_id: 1, credit_account_id: 3, amount: "23.7"},
  {debit_account_id: 1, credit_account_id: 2, amount: "23.7"},
  {debit_account_id: 1, credit_account_id: 4, amount: "23.7"},
  {debit_account_id: 2, credit_account_id: 1, amount: "2.7"}
])

# AccountsBankTransaction table for HABTM relation
AccountsBankTransaction.create!([
  {account_id: 2, bank_transaction_id: 1},
  {account_id: 1, bank_transaction_id: 1},
  {account_id: 2, bank_transaction_id: 2},
  {account_id: 1, bank_transaction_id: 2},
  {account_id: 2, bank_transaction_id: 3},
  {account_id: 1, bank_transaction_id: 3},
  {account_id: 2, bank_transaction_id: 4},
  {account_id: 1, bank_transaction_id: 4},
  {account_id: 1, bank_transaction_id: 5},
  {account_id: 2, bank_transaction_id: 5},
  {account_id: 1, bank_transaction_id: 6},
  {account_id: 2, bank_transaction_id: 6},
  {account_id: 1, bank_transaction_id: 7},
  {account_id: 2, bank_transaction_id: 7},
  {account_id: 1, bank_transaction_id: 8},
  {account_id: 2, bank_transaction_id: 8},
  {account_id: 1, bank_transaction_id: 9},
  {account_id: 2, bank_transaction_id: 9},
  {account_id: 1, bank_transaction_id: 10},
  {account_id: 4, bank_transaction_id: 10},
  {account_id: 1, bank_transaction_id: 11},
  {account_id: 4, bank_transaction_id: 11},
  {account_id: 1, bank_transaction_id: 12},
  {account_id: 4, bank_transaction_id: 12},
  {account_id: 3, bank_transaction_id: 13},
  {account_id: 4, bank_transaction_id: 13},
  {account_id: 3, bank_transaction_id: 14},
  {account_id: 4, bank_transaction_id: 14},
  {account_id: 3, bank_transaction_id: 15},
  {account_id: 4, bank_transaction_id: 15},
  {account_id: 3, bank_transaction_id: 16},
  {account_id: 4, bank_transaction_id: 16},
  {account_id: 3, bank_transaction_id: 17},
  {account_id: 2, bank_transaction_id: 17},
  {account_id: 3, bank_transaction_id: 18},
  {account_id: 2, bank_transaction_id: 18},
  {account_id: 3, bank_transaction_id: 19},
  {account_id: 2, bank_transaction_id: 19},
  {account_id: 1, bank_transaction_id: 20},
  {account_id: 2, bank_transaction_id: 20},
  {account_id: 1, bank_transaction_id: 21},
  {account_id: 2, bank_transaction_id: 21},
  {account_id: 3, bank_transaction_id: 22},
  {account_id: 4, bank_transaction_id: 22},
  {account_id: 3, bank_transaction_id: 23},
  {account_id: 4, bank_transaction_id: 23},
  {account_id: 4, bank_transaction_id: 24},
  {account_id: 2, bank_transaction_id: 24},
  {account_id: 4, bank_transaction_id: 25},
  {account_id: 2, bank_transaction_id: 25},
  {account_id: 4, bank_transaction_id: 26},
  {account_id: 2, bank_transaction_id: 26},
  {account_id: 2, bank_transaction_id: 27},
  {account_id: 4, bank_transaction_id: 27},
  {account_id: 2, bank_transaction_id: 28},
  {account_id: 4, bank_transaction_id: 28},
  {account_id: 2, bank_transaction_id: 29},
  {account_id: 4, bank_transaction_id: 29},
  {account_id: 3, bank_transaction_id: 30},
  {account_id: 1, bank_transaction_id: 30},
  {account_id: 2, bank_transaction_id: 31},
  {account_id: 1, bank_transaction_id: 31},
  {account_id: 4, bank_transaction_id: 32},
  {account_id: 1, bank_transaction_id: 32},
  {account_id: 1, bank_transaction_id: 33},
  {account_id: 2, bank_transaction_id: 33}
])
